install:
  - ps: Start-FileDownload 'https://static.rust-lang.org/dist/rust-nightly-i686-pc-windows-gnu.exe'
  - rust-nightly-i686-pc-windows-gnu.exe /VERYSILENT /NORESTART /DIR="C:\Program Files (x86)\Rust"
  - SET PATH=%PATH%;C:\Program Files (x86)\Rust\bin
  - rustc -V
  - cargo -V
  - cinst 7zip.commandline -x86
  - SET PATH=%PATH%;C:\MinGW\bin;
  - cd sqlite_test/ && mkdir bin\i686-pc-windows-gnu
  - ps: Start-FileDownload "https://www.sqlite.org/2015/sqlite-autoconf-3080803.tar.gz"
  - cmd: 7z x sqlite-autoconf-3080803.tar.gz -o.\ && 7z x sqlite-autoconf-3080803.tar -o.\
  - cd sqlite-autoconf-3080803 && gcc -shared -o sqlite3.dll sqlite3.c -Wl,--output-def,sqlite3.def,--out-implib,libsqlite3.a
  - copy .\libsqlite3.a ..\bin\i686-pc-windows-gnu\ && copy .\sqlite3.dll ..\

build: false

test_script:
  - cargo run --verbose
