install:
  - ps: Start-FileDownload 'https://static.rust-lang.org/dist/rust-nightly-i686-pc-windows-gnu.exe'
  - rust-nightly-i686-pc-windows-gnu.exe /VERYSILENT /NORESTART /DIR="C:\Program Files (x86)\Rust"
  - SET PATH=%PATH%;C:\Program Files (x86)\Rust\bin
  - rustc -V
  - cargo -V
  - ps: Start-FileDownload 'https://download.libsodium.org/libsodium/releases/libsodium-1.0.2-mingw.tar.gz'
  - cinst 7zip.commandline -x86
  - 7z x c:\libsodium-1.0.2-mingw.tar.gz -o c:\libsodium-1.0.2-mingw -y > nul
  - cd libsodium-1.0.2-mingw
  - ls
  - cd ..
  - cd ciTest/
build: false

test_script:
  - cargo test --verbose

  
